# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/messaging.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/messaging.proto\x12\tmessaging\"J\n\x14\x43reateChannelRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x04type\x18\x02 \x01(\x0e\x32\x16.messaging.ChannelType\"(\n\x15\x43reateChannelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"$\n\x14RemoveChannelRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"(\n\x15RemoveChannelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x15\n\x13ListChannelsRequest\"<\n\x14ListChannelsResponse\x12$\n\x08\x63hannels\x18\x01 \x03(\x0b\x32\x12.messaging.Channel\">\n\x15PublishMessageRequest\x12\x14\n\x0c\x63hannel_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\")\n\x16PublishMessageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"/\n\x17SubscribeChannelRequest\x12\x14\n\x0c\x63hannel_name\x18\x01 \x01(\t\"-\n\x15ReceiveMessageRequest\x12\x14\n\x0c\x63hannel_name\x18\x01 \x01(\t\"W\n\x07\x43hannel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x04type\x18\x02 \x01(\x0e\x32\x16.messaging.ChannelType\x12\x18\n\x10pending_messages\x18\x03 \x01(\x05\"0\n\x07Message\x12\x14\n\x0c\x63hannel_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c*\'\n\x0b\x43hannelType\x12\n\n\x06SIMPLE\x10\x00\x12\x0c\n\x08MULTIPLE\x10\x01\x32\xf5\x03\n\rMessageBroker\x12R\n\rCreateChannel\x12\x1f.messaging.CreateChannelRequest\x1a .messaging.CreateChannelResponse\x12R\n\rRemoveChannel\x12\x1f.messaging.RemoveChannelRequest\x1a .messaging.RemoveChannelResponse\x12O\n\x0cListChannels\x12\x1e.messaging.ListChannelsRequest\x1a\x1f.messaging.ListChannelsResponse\x12U\n\x0ePublishMessage\x12 .messaging.PublishMessageRequest\x1a!.messaging.PublishMessageResponse\x12L\n\x10SubscribeChannel\x12\".messaging.SubscribeChannelRequest\x1a\x12.messaging.Message0\x01\x12\x46\n\x0eReceiveMessage\x12 .messaging.ReceiveMessageRequest\x1a\x12.messaging.Messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.messaging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANNELTYPE']._serialized_start=661
  _globals['_CHANNELTYPE']._serialized_end=700
  _globals['_CREATECHANNELREQUEST']._serialized_start=36
  _globals['_CREATECHANNELREQUEST']._serialized_end=110
  _globals['_CREATECHANNELRESPONSE']._serialized_start=112
  _globals['_CREATECHANNELRESPONSE']._serialized_end=152
  _globals['_REMOVECHANNELREQUEST']._serialized_start=154
  _globals['_REMOVECHANNELREQUEST']._serialized_end=190
  _globals['_REMOVECHANNELRESPONSE']._serialized_start=192
  _globals['_REMOVECHANNELRESPONSE']._serialized_end=232
  _globals['_LISTCHANNELSREQUEST']._serialized_start=234
  _globals['_LISTCHANNELSREQUEST']._serialized_end=255
  _globals['_LISTCHANNELSRESPONSE']._serialized_start=257
  _globals['_LISTCHANNELSRESPONSE']._serialized_end=317
  _globals['_PUBLISHMESSAGEREQUEST']._serialized_start=319
  _globals['_PUBLISHMESSAGEREQUEST']._serialized_end=381
  _globals['_PUBLISHMESSAGERESPONSE']._serialized_start=383
  _globals['_PUBLISHMESSAGERESPONSE']._serialized_end=424
  _globals['_SUBSCRIBECHANNELREQUEST']._serialized_start=426
  _globals['_SUBSCRIBECHANNELREQUEST']._serialized_end=473
  _globals['_RECEIVEMESSAGEREQUEST']._serialized_start=475
  _globals['_RECEIVEMESSAGEREQUEST']._serialized_end=520
  _globals['_CHANNEL']._serialized_start=522
  _globals['_CHANNEL']._serialized_end=609
  _globals['_MESSAGE']._serialized_start=611
  _globals['_MESSAGE']._serialized_end=659
  _globals['_MESSAGEBROKER']._serialized_start=703
  _globals['_MESSAGEBROKER']._serialized_end=1204
# @@protoc_insertion_point(module_scope)
